### ISSUE TITLE
URI Character Confusion

### ISSUE THREAD

**Issue by ericadeefox** [BallStateCBER/muncie_events3#25]
Routing/URLS not accepting %2F as a URI character. Sometimes apache rejects %2F & %5C (which is the \ slash) but it weirdly accepts %5C... and every other URI character I tried.

Therefore, tags or locations with symbols in their names cannot be indexed.

**Comment by PhantomWatson** [comment]
(copying from Slack so we have this for reference later)

**Reason:** https://httpd.apache.org/docs/2.2/mod/core.html#allowencodedslashes

**Easy Solution:** Set `AllowEncodedSlashes` to `On`

**Safer Solution:** Set `AllowEncodedSlashes` to `NoDecode` and have the back-end decode `%2F` into `/` and `%5C` into `\` for any string-type route parameters.

**Alternative Solution:** Eliminate slashes from stringy route parameters by storing and searching by slugs. 🐌

**Comment by ericadeefox** [comment]
*Alternative alternative solution:* Eliminate slashes from stringy route parameters by saving all the slashes as something else in the locations.

**Comment by ericadeefox** [comment]
It wouldn't even really be that hard because it's already recognizing `%5C` as `\`.

**Comment by ericadeefox** [comment]
Welp. That was awful.

Now that I have a migration that will definitely fix all of the issues with the actual data in the fields, including removing whitespace, _and_ trim whitespace in the table methods just in case that's not good enough, _I think I can safely say that the existing locations are good for now if we are on top of moderating future events that come through the 2.x site_. Which, like, I never ever want to write that much SQL again in my life, holy diver.

ANYWAY--next step is brainstorming moderation options so that the locations are never this convoluted & jumbled up again.
