### ISSUE TITLE
$this->request->data is deprecated.

### ISSUE THREAD

**Issue by ericadeefox** [BallStateCBER/muncie_events3#35]
`$this->request->data` is a deprecated method, to be replaced with `$this->request->getData()`. However, the two are not analogous. The method for setting custom tags in the Events Controller is dependent upon `$this->request->data`, it works perfectly with that method, but the method _is_ deprecated.

**Comment by PhantomWatson** [comment]
Protip: Anything that's dependent on altering the `$this->request->data` property can be updated thusly:

```
$this->request = $this->request->withData($name, $value);
```

**Comment by ericadeefox** [comment]
Thank you, I'll just update that tomorrow then
