### ISSUE TITLE
Add time validation

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events3#36]
Add validation rules in `EventsTable` for `Events.start_time` and `Events.end_time`.

**Comment by ericadeefox** [comment]
Just for the model, or would we need to do anything to the table in the database as well? e.g. a migration that alters those columns.

**Comment by PhantomWatson** [comment]
Nope, they're already `time` fields and that doesn't need to change.

I just noticed that there's no validation in `EventsTable` that makes `start_time` required or enforces their data type.

**Comment by ericadeefox** [comment]
Ah, cool, I'll get on that right now then.
