### ISSUE TITLE
Pagination formatting issues

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events3#42]
For the `pagination.ctp` element
- I recommend only displaying "first", "prev", "next", and "last" elements when they can be interacted with. I now think that my old idea of displaying those useless elements as kind of a visual placeholder is probably dumb.
- The old pagination element bizarrely used single-quotes for some of its HTML element attributes, which should be fixed. But this only applies to the elements that I recommend removing, so `*shruuuug*`
- The new line that reads "showing X records out of Y total" is a bit weird to me. I recommend one or more of these:
  - Take out "page X of Y" because the `<select>` element already provides that information
  - Take out "showing X records out of Y total" because it's low-priority information that can already be basically discerned from everything else on the screen
  - Change "record(s)" to a string that actually reflects what model is being shown and whether it should be singular or plural. Bonus points for making this automatic! 😀 

As always, feel free to debate any of my recommendations. 😃

**Comment by ericadeefox** [comment]
> I now think that my old idea of displaying those useless elements as kind of a visual placeholder is probably dumb.

Why? I could grey them out when they can't be interacted with.

But the text is just the, like, boilerplate CakePHP 3.x Paginator helper text. I didn't really think about it but yeah it's not very helpful text right now.

**Comment by PhantomWatson** [comment]
It would follow the general rule of web design to reduce clutter and visual complexity by minimizing displaying unnecessary content. We could defer to Victoria and see what her recommendation is.

If pagination worked asynchronously, I think there'd be value to keeping all of the pagination links in the same place on the page and disabling/enabling them when appropriate so they're not hopping around and dodging one's cursor.

**Comment by ericadeefox** [comment]
> We could defer to Victoria and see what her recommendation is.

I'm in favor of this. It's my instinct that placeholders are good because they suggest specifically how to use those particular links, but I'm also not very good with design so I trust other people on it.

How is this for pagination text:
![image](https://user-images.githubusercontent.com/12422542/34058631-b91a64da-e1a9-11e7-8403-76da7e04f2e9.png)

![image](https://user-images.githubusercontent.com/12422542/34058651-d2e7c90c-e1a9-11e7-9a0b-f71fd58658b9.png)

![image](https://user-images.githubusercontent.com/12422542/34058693-faa76452-e1a9-11e7-80e0-79747408c78f.png)

**Comment by PhantomWatson** [comment]
- I'd lowercase "location" and "tag"
 - It might (maybe, _possibly_) read better if it were a bit more nuanced, like "...at [location name]" and "...tagged as [tag name]"
- Bonus points: "Showing X *past/upcoming* events..."
- If non-link linkish elements are displayed, I think they should be very visually distinct. @VictoriaMeldrum  suggests "the text itself needs to be gray, like 50% gray or even lighter"

**Comment by ericadeefox** [comment]
![pagin1](https://user-images.githubusercontent.com/12422542/34059209-0af8261e-e1ac-11e7-9b5c-12a398886350.gif)
![pagin2](https://user-images.githubusercontent.com/12422542/34059210-0c88919e-e1ac-11e7-839c-254d3130b951.gif)

**Comment by ericadeefox** [comment]
I'm gonna close this one since the last screencaps got a :+1:
