### ISSUE TITLE
Upload verify token: Improve or remove?

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events3#51]
**If we want to keep using `App.upload_verify_token` to ensure that uploaded images (probably) came from the event form, we should...**
- Change the value and move where it's defined from from `app.php` to `.env`.
- In `ImagesController::upload()`, verify that `$this->request->getData('timestamp')` was within the last... maybe one hour? Whatever the longest reasonable amount of time would be between loading the form and uploading an image. Otherwise, [the parameters of `ImageManager.setupUpload()`](https://github.com/BallStateCBER/muncie_events3/blob/master/src/Template/Element/images/form.ctp#L117) could be copied and used to construct POST requests that successfully upload images at any point in the future while circumventing the form.

**If we think that verifying the origin of image uploads is unnecessary, we should...**
- Cut out `App.upload_verify_token` and the code related to it

I don't think this token verification prevents any realistic attack. It's good to take extra precautions when file uploads are involved, but I'm leaning toward recommending the latter option.

**Comment by ericadeefox** [comment]
\*shrug\* the files will be uploaded regardless, token verification doesn't stop it.

**Comment by ericadeefox** [comment]
I believed so when I upgraded the image uploading part of the site, but just figured I'd upgrade everything and deal with it if there was any issues from there.

**Comment by PhantomWatson** [comment]
> the files will be uploaded regardless, token verification doesn't stop it.

The current version (when I opened the issue, anyway) gives a "Security code incorrect" error if `$_POST['timestamp']` and `$_POST['token']` fail verification.
