### ISSUE TITLE
Unpublished events being shown

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events3#54]
Events with `approved_by = null` and `published = 0` are still appearing on the front page.

![image](https://user-images.githubusercontent.com/1965565/35164238-a4791f60-fd17-11e7-88a3-39d611ef891b.png)

Check to make sure that unpublished events don't appear in
- the front page
- category pages
- tag pages
- location pages
- user pages
- widget pages
- the mailing list

**Comment by ericadeefox** [comment]
I actually did this intentionally.

See, Jess Fisher has multiple events posted on ME already. Hence her event has `published = 1`. However, it has `approved = 0` because neither of us has reviewed it yet for, y'know, things like tags or if the location isn't correct, anything like that. I expanded moderation in that respect, so that we would be able to moderate events posted by people who still _are_ allowed to publish things.

**Comment by PhantomWatson** [comment]
That's not correct. The database showed `approved_by = null` and `published = 0` for event 5017:
![image](https://user-images.githubusercontent.com/1965565/35167486-c28f9bbc-fd23-11e7-8873-979dadae1d81.png)

**Comment by ericadeefox** [comment]
:headslam: on it.

**Comment by ericadeefox** [comment]
Wait, did you check that just now? Because I approved the event after I got this. So, _something's_ wrong, I just want to make sure it's the right something before I push anything.

**Comment by PhantomWatson** [comment]
That was what was in the database when the error was taking place.

**Comment by ericadeefox** [comment]
Cool, on it.

**Comment by PhantomWatson** [comment]
Sidenote: It looks like the site's policy of only including approved events in mailing list emails has also disappeared and needs to be re-added.

**Comment by ericadeefox** [comment]
This is being a bit tricky to test because, locally, it behaves as expected... so I'm not sure what's going on here, but...

**Comment by ericadeefox** [comment]
Alright, unpublished events now cannot be viewed on the main index nor the category, day, location-based or tag-based indexes. (indices?) Not sure about the month index but honestly I don't even think there's a link to the month index anywhere.
