### ISSUE TITLE
Tag edit form error

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events3#58]
https://muncieevents.com/tags/edit/craftbeer isn't populating the form fields. I think `TagsController::edit()` is missing something like `$this->request = $this->request->withData($tag);`

**Comment by ericadeefox** [comment]
It is also just a mess in general. We've got some issues such as

- [ ] Whatever's keeping it from populating the form fields.
- [ ] It seems to just display the form on default without actually knowing what to display or what tag we have or anything.
- [ ] Submit button for `Update tag #x` needs bootstrapified
- [ ] The flash messages don't actually display until the person leaves the `/tags/edit` or `/tags/manage` page.

**Comment by PhantomWatson** [comment]
> Whatever's keeping it from populating the form fields.

That would be the request data not being populated, given how it's currently coded. `$this->request = $this->request->withData($tagData);` when `$this->request->is('get')` should take care of that.

> The flash messages don't actually display until the person leaves the /tags/edit or /tags/manage page.

It appears that flash messages aren't shown because `insertFlashMessage()` called in the AJAX layout adds messages to the element `#flash_messages`, which doesn't actually exist.

Flash messages get retained and showed upon the next rendering in the default layout because its invocation of the `FlashHelper` is the only thing deleting those messages from the session.

The Data Center handles flash messages with a [custom flash component](https://github.com/BallStateCBER/datacenter-plugin-cakephp3/blob/master/src/Controller/Component/FlashComponent.php), an [element](https://github.com/BallStateCBER/datacenter-plugin-cakephp3/blob/master/src/Template/Element/flash_messages_bootstrap.ctp) added to the default layout, [this code](https://github.com/BallStateCBER/datacenter-plugin-cakephp3/blob/master/src/Template/Layout/ajax.ctp#L25) added to the AJAX layout, and a [JS object](https://github.com/BallStateCBER/datacenter-plugin-cakephp3/blob/master/webroot/js/flash.js). That code could be copied over to Muncie Events.

**Comment by ericadeefox** [comment]
Need to fix the flash message issue and actually remove all of the deprecated code now.

**Comment by ericadeefox** [comment]
I'm not sure that I'll be using the DataCenter flash component just yet, as the other sections of the tag manager still instantaneously display the flash messages... so I'll be figuring out what the difference is between the two.
