### ISSUE TITLE
Search results phrasing

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events3#59]
[This search](https://muncieevents.com/search?filter=After+Hours+Art+Reels&direction=future) results in the message

> Search Results
> 
> 13 matching past events found
> Want to narrow your search? Some upcoming events have this matching tag: after hours art reels
> **No events have been found.**

I suggest changing "No events" to "No upcoming events" so it doesn't seem contradictory.

Also, the link to the "after hours art reels" tag shows the message
> 0 Future Events with Tag: After Hours Art Reels

which contradicts the "some upcoming events have" text. We could just change that to "Some events have this matching tag: [tag name]" or "Search for events with the tag [tag name]".

**Comment by ericadeefox** [comment]
This is relevant to issue #61 as well because that's where the future/upcoming language issue comes into play. So we'll need to change the search into "upcoming" as well.

**Comment by ericadeefox** [comment]
Last three commits were meant for issue #58.
