### ISSUE TITLE
Moderation page / sidebar alert disagreement

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events3#65]
This weekend, the sidebar showed that there were three unapproved events, but the moderation page showed that there were none:

![27152554_10105380477107748_1476609227_n](https://user-images.githubusercontent.com/1965565/35244607-b966bdd2-ff8e-11e7-8b45-9be5a72c5083.png)

**Comment by ericadeefox** [comment]
Issue #56
