### ISSUE TITLE
Automatic publishing disabled

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events3#67]
- A user alerted me to their events not being published as expected. The previous "automatically publish events from trusted users" functionality provided by [`User::canAutopublish()`](https://github.com/BallStateCBER/muncie_events/blob/development/app/Model/User.php#L130) appears to be missing.
 - [This text](https://github.com/BallStateCBER/muncie_events/blob/development/app/View/Events/form.ctp#L46) that explains to users that their event won't be automatically published has been removed too. Adding it back to the form will prevent other users from thinking that the site is broken when their event does not get immediately published.

**Comment by ericadeefox** [comment]
I must've at the time I started working on this, decided we ought to just start moderating _all_ the events, to prevent stuff like poor location names or that sort of thing. But I should've re-added this functionality after I set Slack to notify us whenever any event was posted. Anyway, I've re-added it. Should be no troubles with it now.
