### ISSUE TITLE
Emojione file not being loaded

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events3#68]
````
2018-01-24 23:05:18 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Emojione could not be found.
Request URL: /emojione/lib/js/emojione.min.js
Referer URL: https://muncieevents.com/event/edit/5029
````
This file is loaded in `src/Template/Element/events/form.ctp` but is not present in `webroot`.

**Comment by ericadeefox** [comment]
The `/emojione/` folder was in `.gitignore` and I guess never made its way to production. So I put it on there. Should be OK now.
